### ISSUE TITLE
Suggestion for Font Family!

### ISSUE THREAD

**Issue by cymkd** [panr/framer-x-button-component#1]
Awesome idea! Thanks for the time and effort!
A suggestion: have Font Family selector available above-under Font Size Font Weight

**Comment by panr** [comment]
@vsimak Thanks! But I don't know if it's possible right now. I'm afraid that code components don't have permission to read your system fonts 😢

**Comment by panr** [comment]
Hey, I think I know how to "fix" it ;-) 😎

**Comment by panr** [comment]
@vsimak Enjoy. I hope you'll like it 😏

What's new: `fontFamily`, `textTransform`, `letterSpacing` ;-)

<img width="349" alt="zrzut ekranu 2018-09-19 o 19 56 08" src="https://user-images.githubusercontent.com/1303365/45771723-24724000-bc46-11e8-9d2d-1e3de843a589.png">
